### ISSUE TITLE
Help getting games from IGDB

### ISSUE THREAD

**Issue by darias08** [nunogois/game-search-expo#3]
Hello,

I am trying to find an example of your code that shows how you were able to get the list of games. I want to do something like this with my app, but I am stuck on getting the games to show on my app. 

I don't know if you have created a twitch account to gain access to the list of games and use a token for it, but I am just really confused on how to use this api. Do you have an example code that shows like, Coming soon and all it's games being called? 

 Please let me know if you have some kind of example of code I can see and it would mean so much if you can help. Thank you!!

**Comment by nunogois** [comment]
Hi @darias08,

For game info, I'm using https://github.com/nunogois/igdb-api - A proxy API I wrote around [IGDB](https://www.igdb.com/). Basically `game-search-expo` reaches out to `igdb-api`, which then reaches out to `IGDB`, and returns the game info.

I haven't touched `igdb-api` in a while, but if you check the code, you can see that it needs 2 environment variables set when running:
https://github.com/nunogois/igdb-api/blob/ed2b5abb7657cb63e50d7a6773c3879b1d553e80/server.js#L32

 - CLIENT_ID
 - CLIENT_SECRET
 
Which you can get by following the steps here: https://api-docs.igdb.com/#about
 
If you check https://github.com/nunogois/igdb-api/blob/ed2b5abb7657cb63e50d7a6773c3879b1d553e80/server.js#L25 - This line also checks a `TOKEN` environment variable to make sure the requests you're making have access to your own instance of the proxy. This one is a custom one, unrelated to the 2 above. 
 
So, after cloning the `igdb-api` repo, you could make a local `.env` file that would look like:
 
```sh
CLIENT_ID=YOUR_IGDB_CLIENT_ID
CLIENT_SECRET=YOUR_IGDB_CLIENT_SECRET
TOKEN=YOUR_OWN_CUSTOM_RANDOM_TOKEN
```

After installing dependencies, e.g. running `yarn`, you could then start it by running `yarn start`.

Now you can use something like [Postman](https://www.postman.com/) or [Insomnia](https://insomnia.rest/) (or anything else) to make a request to it:
 - **GET** `http://localhost:3000/games` with Authorization `Bearer YOUR_OWN_CUSTOM_RANDOM_TOKEN` - Should retrieve some recent popular games;
 - **GET** `http://localhost:3000/games?search=fortnite` with Authorization `Bearer YOUR_OWN_CUSTOM_RANDOM_TOKEN` - Should retrieve search results for `fortnite`;
 
Looking at the code, it's possible that `igdb-api` assumes you have a `redis` instance running, which may not be the case. If you face issues, you can either try running a `redis` instance locally or comment any `redis` related lines of code in `server.js` before running.

If the requests work, great! That means that if your app is able to make a similar request, it should work as well. For `game-search-expo` specifically, that means setting these environment variables:

 - API: https://github.com/nunogois/game-search-expo/blob/c480a336c1335effdf1c3daebb0199d7323461f7/hooks/Games.ts#L65 - The URL for our `igdb-api` instance;
 - TOKEN: https://github.com/nunogois/game-search-expo/blob/c480a336c1335effdf1c3daebb0199d7323461f7/hooks/Games.ts#L57 - The TOKEN you set above for our `igdb-api` instance;
 
A good thing about using a proxy API is that your `CLIENT_ID` and `CLIENT_SECRET` values are protected by only existing on the server, instead of using them to connect your app to IGDB directly and possibly exposing them.

## Conclusion

This tells me that I should probably rewrite `igdb-api` to a better version sometime, more reusable and with better docs 😅 

Anyways, I hope this helped understanding my thought process at the time, and even if you end up not using my `igdb-api` maybe it's good info to write your own implementation. [IGDB API docs](https://api-docs.igdb.com/#about) are a great resource.

If you face any issues let me know (please share details about the issue you're facing, e.g. error message) and I can try to help!

**Comment by darias08** [comment]
Hi @nunogois!

Thank you so much for your help! :-) 

I am been meaning to ask what direction you recommend for someone who wants to build a gaming library for users to explore. Like, I want to retrieve what's new, what's popular, recently released, and recommended games to play.  I am not seeing it on their website under the endpoints section. I have seen some other apps that can invoke those endpoints but, I am just stuck on how I can get them.  I am trying to create a homepage that lets users explore those topics. Anyway I can get those list of games for that section?

Just to give you a heads up I am really new when it comes to using API so lol I am sorry if I sound confused about this 😅

**Comment by nunogois** [comment]
Hi @darias08,

No problem!

I would recommend checking out the IGDB docs, specifically the [examples](https://api-docs.igdb.com/#examples) and how they show how you can write a query suited to your needs. There's nothing better than setting it up in Postman for example and messing around with it yourself.

Once you figure out a couple of requests returning the information you need, you can make your own proxy API with all the endpoints you need. Each of them would then request your respective queries to IGDB and return the data you want.

Of course, you probably can't count on IGDB for every single need you have, so you'll probably need to implement your own custom logic on your proxy API.

This is getting very off-topic for `game-search-expo` so I'll close this for now. 
I hope this helps and https://github.com/nunogois/igdb-api can also be a good resource for what you wish to do. 
Feel free to reach out in some other way if you need to.

**Comment by darias08** [comment]
Hi again! 

So I wanted to test out your app to get a better understanding of how it works, but I am running through some errors trying to retrieve your app. 

Here's the error message I am getting at:
https://drive.google.com/file/d/1qxXay-IjTiO8Qb-oNX53cr1bdeTgZSTX/view?usp=sharing

I have tried using multiple methods on the internet to fix this error, but none seem to work. Any thoughts on how I can get this to work?
