### ISSUE TITLE
How did you create a similar games infinite loop?

### ISSUE THREAD

**Issue by darias08** [nunogois/game-search-expo#5]
Hello!

I was wondering how you were able to create a infinite loop through the similar_games section in your Detail Screen? For example, I am seeing in your short clip you clicked on a game and within that it has a list of similar games. Once you clicked on one of them it brought you to the same screen, but with that game's information showing. 

I have tried using several methods like `navigation.push()` which suppose to push the data to the detail screen and show the new data. Doing so will work but it won't go any deeper or further if I were to click another similar_games within that game. It just gives me an error saying it's `undefined`.  

Here's a short video example of what I am talking:

https://user-images.githubusercontent.com/58616895/208793553-fc8bb183-a777-442f-b314-5acab59a8f8d.mp4

As you can see here, I can't get the image cover to display because it would say the `image_id` is `undefined` and I am not sure why, when it should be under the same as `/games` api if were to use `item.cover.image_id` Another thing about this is that, you can see the name and the similar games disappears when I go to the third screen (final screen point). 

How can I essentially keep all data consistent when the user navigates each game through similar_games?

Please let me know what you think and if this topic isn't relatable then please close this post. I just wanted to ask about this since you have it working on your project and I am confused how to get this to work.

**Comment by nunogois** [comment]
Hey @darias08,

Glad you're progressing with your app.

I think I mentioned it before, but I think it would be great for you if you forked (and star ⭐ them while you're at it) both [game-search-expo](https://github.com/nunogois/game-search-expo) and [igdb-api](https://github.com/nunogois/igdb-api) to check how they work together, learn more about how I achieved this and maybe even contribute to them.

Maybe this will help you with your similar games question:
https://github.com/nunogois/igdb-api/blob/ed2b5abb7657cb63e50d7a6773c3879b1d553e80/server.js#L125-L128

https://github.com/nunogois/game-search-expo/blob/c480a336c1335effdf1c3daebb0199d7323461f7/hooks/Games.ts#L37-L46

https://github.com/nunogois/game-search-expo/blob/c480a336c1335effdf1c3daebb0199d7323461f7/screens/GameDetailScreen.tsx#L125-L144

Since you seem to be asking for help in multiple places, open-sourcing and linking your project would also be a big help towards people helping you.

**Comment by darias08** [comment]
Hello! 

Thank you so much for your help! I was able to get the similar games to work. I'll definitely play around with this more, but to be honest about your project it's that you are using typescript which is different from mine because I am using javascript. So I am not sure if I am able to merge my project with yours. Anyways, this should definitely be my last question and I apologize if I asked a several times on here. This is my first time building a react-native mobile app 😅

**Comment by darias08** [comment]
Anyways, thanks a ton @nunogois! Please have a wonderful christmas and happy new years! :D
